In [ ]:
# Import Libraries
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.datasets import mnist

# Load Dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize Images (0-255 -> 0-1)
x_train = x_train / 255.0
x_test = x_test / 255.0

# Build Deep Learning Model
model = Sequential([
    Flatten(input_shape=(28, 28)),      # Convert 28x28 image to 784 values
    Dense(128, activation='relu'),      # Hidden Layer 1
    Dense(64, activation='relu'),       # Hidden Layer 2
    Dense(10, activation='softmax')     # Output Layer (10 digits)
])

# Compile Model
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train Model
model.fit(
    x_train,
    y_train,
    epochs=5,
    batch_size=32,
    validation_split=0.2
)

# Evaluate Model
loss, accuracy = model.evaluate(x_test, y_test)

print("Test Accuracy:", accuracy)

# Predict First Test Image
prediction = model.predict(x_test[:1])

print("Predicted Digit:", prediction.argmax())
print("Actual Digit:", y_test[0])

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


c:\Users\VAMSI KUMAR REDDY\anaconda3\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 16s 8ms/step - accuracy: 0.9223 - loss: 0.2690 - val_accuracy: 0.9597 - val_loss: 0.1414
Epoch 2/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.9657 - loss: 0.1121 - val_accuracy: 0.9672 - val_loss: 0.1073
Epoch 3/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.9752 - loss: 0.0776 - val_accuracy: 0.9678 - val_loss: 0.1080
Epoch 4/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 12s 8ms/step - accuracy: 0.9822 - loss: 0.0570 - val_accuracy: 0.9731 - val_loss: 0.0968
Epoch 5/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - accuracy: 0.9855 - loss: 0.0443 - val_accuracy: 0.9765 - val_loss: 0.0845
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9774 - loss: 0.0749
Test Accuracy: 0.977400004863739
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 244ms/step
Predicted Digit: 7
Actual Digit: 7


In [11]:
# Import Metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

# Predict all test images
y_pred = model.predict(x_test)

# Convert probabilities to class labels
y_pred_classes = y_pred.argmax(axis=1)

# Calculate Metrics
accuracy = accuracy_score(y_test, y_pred_classes)
precision = precision_score(y_test, y_pred_classes, average='weighted')
recall = recall_score(y_test, y_pred_classes, average='weighted')
f1 = f1_score(y_test, y_pred_classes, average='weighted')

# Print Metrics
print("\n===== Evaluation Metrics =====")
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_classes))

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred_classes))


313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

===== Evaluation Metrics =====
Accuracy : 0.9774
Precision: 0.9774124191494186
Recall   : 0.9774
F1 Score : 0.9773768950964355

Confusion Matrix:
[[ 971    0    1    1    0    1    3    0    2    1]
 [   0 1129    1    0    0    1    2    0    2    0]
 [   6    1 1012    2    1    0    2    4    4    0]
 [   0    2    4  989    0    8    0    4    3    0]
 [   0    1    6    0  962    0    0    1    1   11]
 [   4    0    0    7    1  872    4    0    3    1]
 [   3    2    0    1    6    5  939    0    2    0]
 [   3    4    9    2    1    0    0  997    3    9]
 [   3    0    5    8    6    9    5    2  933    3]
 [   3    5    0    6   10    6    1    4    4  970]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.97      0.98      0.98      1032
           3       0.97      0.98      0

   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.5/351.2 MB 284.2 kB/s eta 0:20:34
   ---------------------------------------- 0.5/351.2 MB 284.2 kB/s eta 0:20:34
   ---------------------------------------- 0.5/351.2 MB 28


[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\VAMSI KUMAR REDDY\anaconda3\Lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "c:\Users\VAMSI KUMAR REDDY\anaconda3\Lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ~~~~~~~~~~~~~^^^^^
  File "c:\Users\VAMSI KUMAR REDDY\anaconda3\Lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ~~~~~~~~~~~~~^^^^^
  File "c:\Users\VAMSI KUMAR REDDY\anaconda3\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
                  ~~~~~~~~~~~~~~^^^^^
  File "c:\Users\VAMSI KUMAR REDDY\anaconda3\Lib\http\client.py", lin

In [9]:
import tensorflow as tf

print("TensorFlow Version:", tf.__version__)

TensorFlow Version: 2.21.0
