RANDOM NUMBERS


In [1]:
import numpy as np

print("----- RANDOM NUMBERS -----")

# Random decimal
print("Random Decimal:")
print(np.random.random())

# Five random decimals
print("\nFive Random Decimals:")
print(np.random.random(5))

# Random integer
print("\nRandom Integer (1-9):")
print(np.random.randint(1,10))

# Dice
print("\nDice Roll:")
print(np.random.randint(1,7))

# Ten random integers
print("\n10 Random Numbers:")
print(np.random.randint(1,101,10))

# Random choice
students = np.array(["Arun","Bala","John","Priya"])
print("\nRandom Student:")
print(np.random.choice(students))

# Two random students
print("\nTwo Random Students:")
print(np.random.choice(students,2))

# Shuffle
numbers = np.array([1,2,3,4,5])
np.random.shuffle(numbers)
print("\nShuffled Array:")
print(numbers)

# Random seed
np.random.seed(42)
print("\nRandom Seed:")
print(np.random.randint(1,100,5))

----- RANDOM NUMBERS -----
Random Decimal:
0.9683848946867103

Five Random Decimals:
[0.05686802 0.8152762  0.90415116 0.45776257 0.45667587]

Random Integer (1-9):
4

Dice Roll:
5

10 Random Numbers:
[85 31 95 44 51 75  3 74 47 21]

Random Student:
John

Two Random Students:
['Arun' 'Bala']

Shuffled Array:
[4 5 1 2 3]

Random Seed:
[52 93 15 72 61]


DATA MANIPULATION AND INDEXING

In [2]:
import numpy as np

print("----- DATA MANIPULATION & INDEXING -----")

marks = np.array([70,80,90,60,75])

print("Original Array:", marks)

print("\nPositive Indexing")
print(marks[0])
print(marks[3])

print("\nNegative Indexing")
print(marks[-1])
print(marks[-2])

print("\nSlicing")
print(marks[1:4])

a = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print("\n2D Array")
print(a)

print("\nElement [0,0]:", a[0,0])
print("Element [1,2]:", a[1,2])
print("Element [2,1]:", a[2,1])

print("\nSecond Row")
print(a[1])

print("\nSecond Column")
print(a[:,1])

----- DATA MANIPULATION & INDEXING -----
Original Array: [70 80 90 60 75]

Positive Indexing
70
60

Negative Indexing
75
60

Slicing
[80 90 60]

2D Array
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Element [0,0]: 10
Element [1,2]: 60
Element [2,1]: 80

Second Row
[40 50 60]

Second Column
[20 50 80]


FILTERING


In [3]:
import numpy as np

print("----- FILTERING -----")

marks = np.array([45,78,90,55,82,60,70])

print("Original:", marks)

print("\nGreater than 60")
print(marks[marks>60])

print("\nLess than 60")
print(marks[marks<60])

print("\nGreater than or Equal to 60")
print(marks[marks>=60])

print("\nEqual to 60")
print(marks[marks==60])

print("\nNot Equal to 60")
print(marks[marks!=60])

print("\nBetween 60 and 80")
print(marks[(marks>=60)&(marks<=80)])

print("\nLess than 50 OR Greater than 80")
print(marks[(marks<50)|(marks>80)])

numbers=np.array([1,2,3,4,5,6,7,8])

print("\nEven Numbers")
print(numbers[numbers%2==0])

print("\nOdd Numbers")
print(numbers[numbers%2!=0])

----- FILTERING -----
Original: [45 78 90 55 82 60 70]

Greater than 60
[78 90 82 70]

Less than 60
[45 55]

Greater than or Equal to 60
[78 90 82 60 70]

Equal to 60
[60]

Not Equal to 60
[45 78 90 55 82 70]

Between 60 and 80
[78 60 70]

Less than 50 OR Greater than 80
[45 90 82]

Even Numbers
[2 4 6 8]

Odd Numbers
[1 3 5 7]


STATISTICS


In [4]:
import numpy as np

print("----- STATISTICS -----")

data = np.array([10,20,30,40,50])

print("Data:", data)

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Range:", np.max(data)-np.min(data))
print("Variance:", np.var(data))
print("Standard Deviation:", np.std(data))

print("25th Percentile:", np.percentile(data,25))
print("50th Percentile:", np.percentile(data,50))
print("75th Percentile:", np.percentile(data,75))

----- STATISTICS -----
Data: [10 20 30 40 50]
Mean: 30.0
Median: 30.0
Minimum: 10
Maximum: 50
Range: 40
Variance: 200.0
Standard Deviation: 14.142135623730951
25th Percentile: 20.0
50th Percentile: 30.0
75th Percentile: 40.0


AGGREGATION


In [5]:
import numpy as np

print("----- AGGREGATION -----")

sales = np.array([100,200,150,300,250])

print("Sales:", sales)

print("Total:", np.sum(sales))
print("Average:", np.mean(sales))
print("Minimum:", np.min(sales))
print("Maximum:", np.max(sales))
print("Number of Records:", sales.size)

data = np.array([
    [10,20,30],
    [40,50,60]
])

print("\n2D Array")
print(data)

print("\nTotal Sum")
print(np.sum(data))

print("\nColumn-wise Sum")
print(np.sum(data,axis=0))

print("\nRow-wise Sum")
print(np.sum(data,axis=1))

print("\nColumn-wise Mean")
print(np.mean(data,axis=0))

----- AGGREGATION -----
Sales: [100 200 150 300 250]
Total: 1000
Average: 200.0
Minimum: 100
Maximum: 300
Number of Records: 5

2D Array
[[10 20 30]
 [40 50 60]]

Total Sum
210

Column-wise Sum
[50 70 90]

Row-wise Sum
[ 60 150]

Column-wise Mean
[25. 35. 45.]


SAVING DATA

In [6]:
import numpy as np

print("----- SAVING DATA -----")

marks = np.array([70,80,90,60,75])

# Save as NumPy file
np.save("marks.npy", marks)
print("marks.npy saved")

# Load NumPy file
loaded = np.load("marks.npy")
print("Loaded:", loaded)

# Save as Text
np.savetxt("marks.txt", marks)
print("marks.txt saved")

# Load Text
loaded_text = np.loadtxt("marks.txt")
print("Loaded Text:", loaded_text)

# Save CSV
data = np.array([
    [101,75],
    [102,85],
    [103,90]
])

np.savetxt("data.csv", data, delimiter=",", fmt="%d")
print("data.csv saved")

# Load CSV
loaded_csv = np.loadtxt("data.csv", delimiter=",")
print("Loaded CSV:")
print(loaded_csv)

----- SAVING DATA -----
marks.npy saved
Loaded: [70 80 90 60 75]
marks.txt saved
Loaded Text: [70. 80. 90. 60. 75.]
data.csv saved
Loaded CSV:
[[101.  75.]
 [102.  85.]
 [103.  90.]]
