# Experiment 4: Artificial Neural Network using Backpropagation

**Aim:** Build an Artificial Neural Network by implementing the Backpropagation algorithm from scratch and test it on an appropriate dataset.

In [1]:
# Step 1: Prepare a small dataset (hours studied / slept -> exam result normalized)
import numpy as np

X = np.array([[2, 9], [1, 5], [3, 6]], dtype=float)
y = np.array([[92], [86], [89]], dtype=float)

X = X / np.amax(X, axis=0)   # normalize inputs
y = y / 100                  # normalize output
print("X (normalized):\n", X)
print("y (normalized):\n", y)

X (normalized):
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
y (normalized):
 [[0.92]
 [0.86]
 [0.89]]


In [2]:
# Step 2: Implement the Backpropagation algorithm from scratch
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

np.random.seed(1)
input_neurons, hidden_neurons, output_neurons = 2, 3, 1
epochs, lr = 7000, 0.1

wh = np.random.uniform(size=(input_neurons, hidden_neurons))
bh = np.random.uniform(size=(1, hidden_neurons))
wout = np.random.uniform(size=(hidden_neurons, output_neurons))
bout = np.random.uniform(size=(1, output_neurons))

for epoch in range(epochs):
    # Forward pass
    hidden_input = np.dot(X, wh) + bh
    hidden_output = sigmoid(hidden_input)
    final_input = np.dot(hidden_output, wout) + bout
    final_output = sigmoid(final_input)

    # Backward pass
    error = y - final_output
    d_output = error * sigmoid_derivative(final_output)
    error_hidden = d_output.dot(wout.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)

    wout += hidden_output.T.dot(d_output) * lr
    bout += np.sum(d_output, axis=0, keepdims=True) * lr
    wh += X.T.dot(d_hidden) * lr
    bh += np.sum(d_hidden, axis=0, keepdims=True) * lr

print("Training complete.")

Training complete.


In [3]:
# Step 3: Display results
print("Input:\n", X)
print("\nActual Output:\n", y)
print("\nPredicted Output:\n", final_output)

Input:
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output:
 [[0.92]
 [0.86]
 [0.89]]

Predicted Output:
 [[0.89401252]
 [0.87968827]
 [0.89535366]]
